### ISSUE TITLE
Duplication of "bedroom light" in text for "turn the bedroom light on"

### ISSUE THREAD

**Issue by koenvervloesem** [synesthesiam/rhasspy-hassio-addon#17]
This is on a clean install of Rhasspy in a virtual environment:

Relevant part of `sentences.ini`:

```
[ChangeLightState]
light_name = (living room lamp | garage light | <ChangeLightColor.light_name>) {name}
light_state = (on | off) {state}

turn <light_state> [the] <light_name>
turn [the] <light_name> <light_state>

[ChangeLightColor]
light_name = (bedroom light) {name}
color = (red | green | blue) {color}

set [the] <light_name> [to] <color>
make [the] <light_name> <color>
```

Go to **Sentences** tab, enter "turn the bedroom light on", click on **Get Intent**.

Result:

"text": "turn the bedroom light bedroom light on"

The duplication of "bedroom light" doesn't happen in "turn the living room lamp on". This has probably something to do with the fact that "bedroom light" is referred to by `<ChangeLightColor.light_name>` in the rule `light_name` in the intent `SetLightState`.

The same happens in Dutch.

**Comment by koenvervloesem** [comment]
And with "The same happens in Dutch" I mean that it also happens when I create such a `sentences.ini` in Dutch; the default Dutch `sentences.ini` doesn't use such a rule.

**Comment by synesthesiam** [comment]
I've fixed this in the default English `sentences.ini`. My new intent recognizer (`fsticuffs`) actually supports nested tags (unlike the others), so this revealed a bug in the `sentences.ini` file -- two levels of `{name}` tags. Thanks for noticing this!

**Comment by koenvervloesem** [comment]
I still see this error happening, with OpenFST, fuzzywuzzy and Rasa:

```
"intent":
"entities":
0:
"end": 21
"entity": "name"
"raw_value": "slaapkamerlamp"
"start": 7
"value": "slaapkamerlamp"
1:
"end": 36
"entity": "name"
"raw_value": "slaapkamerlamp"
"start": 7
"value": "slaapkamerlamp"
2:
"end": 40
"entity": "state"
"raw_value": "aan"
"start": 37
"value": "aan"
"intent":
"confidence": 1
"name": "ChangeLightState"
"raw_text": "zet de slaapkamerlamp slaapkamerlamp aan"
"raw_tokens":
0: "zet"
1: "de"
2: "slaapkamerlamp"
3: "slaapkamerlamp"
4: "aan"
"slots":
"name": "slaapkamerlamp"
"state": "aan"
"speech_confidence": 1
"text": "zet de slaapkamerlamp slaapkamerlamp aan"
"time_sec": 0.0016121864318847656
"tokens":
0: "zet"
1: "de"
2: "slaapkamerlamp"
3: "slaapkamerlamp"
4: "aan"
```

**Comment by synesthesiam** [comment]
Can you post your `sentences.ini` file? Is this only happening when you speak that sentence, or when you type "zet de slaapkamerlamp aan" as well?

**Comment by koenvervloesem** [comment]
This is a minimal non-working example `sentences.ini` for the Dutch profile:

```
[ChangeLightState]
light_name = (woonkamerlamp | garagelamp | <ChangeLightColor.light_name>) {name}
light_state = (aan | uit) {state}

zet [de] <light_name> <light_state>

[ChangeLightColor]
light_name = (slaapkamerlamp) {name}
color = (rood | groen | blauw) {color}

verander [de] <light_name> naar <color>
maak [de] <light_name> <color>
```

This works for 'zet de woonkamerlamp aan', but not for 'zet de slaapkamerlamp aan' (see the output in my previous message). This is also happening when I type the sentence in the Speech tab and click on 'Get intent'.

**Comment by synesthesiam** [comment]
This is caused by having two levels of `{name}` tags (`slaapkamerlamp` already has a `{name}`). I need to fix this in the underlying code, but for now you can just rearrange the first `light_name` like this:

```
[ChangeLightState]
light_name = (woonkamerlamp | garagelamp) {name} |  <ChangeLightColor.light_name>
```

**Comment by koenvervloesem** [comment]
Right, that makes sense. Thanks!
